management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  application:
    name: qrcode
  log-dir: ${LOG_DIR:/var/log/qrcode}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:test}
  servlet:
    multipart:
      max-request-size: 52428800
      max-file-size: 52428800

